---
title: "Scrape Comments"
output: html_notebook
---

# Packages

```{r}
#devtools::install_github("soodoku/tuber")

pacman::p_load(tidyverse, tuber, magrittr, stringi, qdapRegex, purrr, lubridate, ggthemes, httr, plyr, svMisc)

```

# Authentication

```{r}
key <- "AIzaSyDmV5jHx7c8GeAmpTkv6To_ERdkZ_HNl70"

client_id <- "580511698053-p8mu77kktkcvb503g9q737svu9gcq101.apps.googleusercontent.com"

client_key <- "Y0eW96yy-WRg90RZjVJS615o"

tuber::yt_oauth(client_id, client_key)

```

# Read in TXT

```{r}
amazingatheist <- read_file("text/amazingatheist.txt")
armored <- read_file("text/armored.txt")
logicked <- read_file("text/logicked.txt")
thunder <- read_file("text/thunder.txt")
sargon <- read_file("text/sargon.txt")


```

# Extract URLs

```{r}

extract_video_ids <- function(video_list) {

video_list %<>% 
  stri_replace_all_fixed(" ", "") %>% 
  stri_replace_all_charclass("\\p{WHITE_SPACE}", "")

url <- rm_between(video_list, "URL:", "Description", extract = TRUE)

imp_vec <- as.vector(url[[1]]) %>% 
  str_replace(pattern = "(.*v\\=)", "")

return(imp_vec)
}

armored_ids <- extract_video_ids(armored)
amazingatheist_ids <- extract_video_ids(amazingatheist)
logicked_ids <- extract_video_ids(logicked)
thunder_ids <- extract_video_ids(thunder)
sargon_ids <- extract_video_ids(sargon)

head(armored_ids)
head(amazingatheist_ids)
head(logicked_ids)
head(thunder_ids)
head(sargon_ids)

```
# GetAllComments

```{r}
get_all_comments2 <- function(video_id = NULL, ...) {
  yt_check_token <- function() {
    app_token <- getOption("google_token")
    if (is.null(app_token)) stop("Please get a token using yt_oauth().\n")
  }

  tuber_GET <- function(path, query, ...) {
    yt_check_token()

    req <- GET(
      "https://www.googleapis.com", path = paste0("youtube/v3/", path),
      query = query, config(token = getOption("google_token")), ...
    )

    tuber_check <- function(req) {
      if (req$status_code < 400) return(invisible())

      stop("HTTP failure: ", req$status_code, "\n", call. = FALSE)
    }

    tuber_check(req)
    res <- content(req)

    res
  }

  querylist <- list(
    videoId = video_id, part = "id,replies,snippet",
    maxResults = 100
  )
  res <- tuber_GET("commentThreads", querylist, ...)
  simple_res <- lapply(res$items, function(x) {
    unlist(x$snippet$topLevelComment$snippet)
  })
  simpler_res <- ldply(simple_res, rbind)
  simpler_res$parentId <- NA
  n_replies <- sapply(res$items, function(x) {
    unlist(x$snippet$totalReplyCount)
  })
  if (sum(n_replies) > 1) {
    replies <- lapply(res$items[n_replies > 0], function(x) {
      unlist(x$replies$comments)
    })
    simpler_rep <- ldply(replies, rbind)
    names(simpler_rep) <- gsub("snippet.", "", names(simpler_rep))
    simpler_rep <- subset(simpler_rep, select = -c(
      kind,
      etag, id
    ))
    agg_res <- plyr::rbind.fill(simpler_res, simpler_rep)
  }
  agg_res <- simpler_res
  page_token <- res$nextPageToken
  while (is.character(page_token)) {
    querylist$pageToken <- page_token
    a_res <- tuber_GET("commentThreads", querylist, ...)
    simple_res <- lapply(a_res$items, function(x) {
      unlist(x$snippet$topLevelComment$snippet)
    })
    simpler_res <- ldply(simple_res, rbind)
    simpler_res$parentId <- NA
    n_replies <- sapply(a_res$items, function(x) {
      unlist(x$snippet$totalReplyCount)
    })
    if (sum(n_replies) > 1) {
      replies <- lapply(a_res$items[n_replies > 0], function(x) {
        unlist(x$replies$comments)
      })
      simpler_rep <- ldply(replies, rbind)
      names(simpler_rep) <- gsub("snippet.", "", names(simpler_rep))
      simpler_rep <- subset(simpler_rep, select = -c(
        kind,
        etag, id
      ))
      agg_res <- plyr::rbind.fill(simpler_res, simpler_rep, agg_res)
      page_token <- a_res$nextPageToken
    }
    agg_res <- plyr::rbind.fill(simpler_res, agg_res)
    page_token <- a_res$nextPageToken
  }
  agg_res %>%
    as.data.frame()
}

```


# Scraper Function

```{r}

# ids <- c(amazingatheist_ids[1:2], "ss", amazingatheist_ids[3])
readkey <- function() {
    line <- readline(prompt = "Are you there? Press [enter]")
}

authentication <- function() {
  beepr::beep(5)
  readkey()
  auth_token <- ".httr-oauth"
  if (file.exists(auth_token)) file.remove(auth_token)

  client_id <- "580511698053-p8mu77kktkcvb503g9q737svu9gcq101.apps.googleusercontent.com"

  client_key <- "Y0eW96yy-WRg90RZjVJS615o"

  tuber::yt_oauth(client_id, client_key)
}


extract_comments <- function(ids, n, youtuber) {
  comments <- list()
  cat("Starting loop. Sit back and get a tea. This might take a while...  ( ͡° ͜ʖ ͡°)\n")
  for (jj in n:length(ids)) {
#    svMisc::progress(jj)
    outcome <- tryCatch({
      get_all_comments2(ids[jj])
    }, 
    error = function(e){
      e
    })
    if (is.data.frame(outcome)) { #Not sure what this does
      comments[[jj]] <- outcome
    } else if (str_detect(outcome$message, "401")) { #if Error Message include 401
      cat("\n Loop stopped on iteration ", jj)
      cat("\n", outcome$message)
      message("\n YouTube Authentication needed!")
      cat("\n Saving data for safety...")
      save(comments, file = paste0("data/", youtuber, "_comments_",  n, "_", jj, ".Rdata"))     
      cat("\t Done! \n")
      authentication()
      cat("\n Waiting for 10 seconds...")
      Sys.sleep(10)                
      cat("\t Done! \n Continuing...")
      comments[[jj]] <- get_all_comments2(ids[jj])
    } else if (str_detect(outcome$message, "400")) { #if Error Message include 400
      cat("\n", outcome$message)
      cat("\n Encountered problem at iteration ", jj)
      cat("\n Saving data for safety...")
      save(comments, file = paste0("data/", youtuber, "_comments_",  n, "_", jj, ".Rdata"))     
      cat("\t Done!")
      cat("\n Waiting for 20 seconds and..")
      Sys.sleep(20)
      cat("\t trying again\n")
      comments[[jj]] <- get_all_comments2(ids[jj])
      cat("\n Puuh... this worked. Deleting file.\n")
      file.remove(paste0("data/", youtuber, "_comments_",  n, "_", jj, ".Rdata"))
    } else if (str_detect(outcome$message, "403")) { #if Error Message include 403
      cat("\n", outcome$message)
      cat("\n Encountered problem at iteration ", jj)
      Sys.sleep(10)
      cat("\n Skipping", jj, "\n")
      next
    }
    cat(paste0("\t", jj)) 
  }   # End of the for loop
  cat("\n Binding rows. Might take while.. \t")
  comments <- suppressWarnings(bind_rows(comments))
  cat("Done!\n ")
  cat("\n Saving data one last time...")
  save(comments, file = paste0("data/", youtuber, "_comments_",  n, "_", jj, ".Rdata"))
  cat("\t Done!\n")
  if (jj == length(ids)) beepr::beep(8)
  cat(paste("\n Congratulations! You just succesfully mined", nrow(comments), "comments from", jj, "YouTube Videos"))
  return(comments)
}

```



# Armored Skeptic

## Scraping

```{r}
armored_comments <- list()
for (jj in seq_along(armored_ids)) {  
  logicked_comments[[jj]] <- get_all_comments2(logicked_ids[jj])
  cat(jj)
}
```

# Amazing Atheist

## Scraping

```{r}

## Try 1
amazingatheist_comments1 <- extract_comments(amazingatheist_ids, 1, "amazingatheist")

## Try 2

amazingatheist_comments2 <- extract_comments(amazingatheist_ids, 934, "amazingatheist")

amazingatheist_comments <- rbind(
  suppressWarnings(bind_rows(get(load("data/amazingatheist_comments_1_238.Rdata")))),
  suppressWarnings(bind_rows(get(load("data/amazingatheist_comments_1_470.Rdata")))),
  suppressWarnings(bind_rows(get(load("data/amazingatheist_comments_1_748.Rdata")))),
  suppressWarnings(bind_rows(get(load("data/amazingatheist_comments_1_848.Rdata")))),
  suppressWarnings(bind_rows(get(load("data/amazingatheist_comments_1_934.Rdata")))),
  suppressWarnings(bind_rows(get(load("data/amazingatheist_comments_934_1448.Rdata"))))
)

save(amazingatheist_comments, file = "data/amazingatheist_comments.Rdata")
```

# Logicked

## Scraping

```{r}

logicked_comments <- list()
for (jj in seq_along(logicked_ids)) {  
  logicked_comments[[jj]] <- get_all_comments2(logicked_ids[jj])
  cat(jj)
}

logicked_comments1 <- list()
logicked_ids1 <- logicked_ids[75:length(logicked_ids)]
for (jj in seq_along(logicked_ids1)) {  
  logicked_comments1[[jj]] <- get_all_comments2(logicked_ids1[jj])
  cat(jj)
}

logicked_data1 <- bind_rows(logicked_comments)
logicked_data2 <- bind_rows(logicked_comments1)

logicked_comments <- rbind(logicked_data1, logicked_data2)

#save(logicked_comments, file = "data/logicked_comments.Rdata")


```



# thunderfoot

## Scraping

```{r}
thunder_comments <- list()
for (jj in seq_along(thunder_ids)) {  
  thunder_comments[[jj]] <- get_all_comments2(thunder_ids[jj])
  cat(paste0("\t",jj))
  BRRR::skrrrahh(jj)
}

thunder_comments1 <- bind_rows(thunder_comments)

save(thunder_comments1, file = "data/thunder1.Rdata")

thunder_ids1 <- thunder_ids[183:length(thunder_ids)]
thunder_comments_1 <- list()
for (jj in seq_along(thunder_ids)) {  
  thunder_comments_1[[jj]] <- get_all_comments2(thunder_ids1[jj])
  cat(paste0("\t",jj))
  BRRR::skrrrahh(jj)
}

thunder_comments_2 <- bind_rows(thunder_comments_1)

save(thunder_comments_2, file = "data/thunder2.Rdata")

thunder_ids2 <- thunder_ids1[199:length(thunder_ids1)]
thunder_comments_22 <- list()
for (jj in seq_along(thunder_ids2)) {  
  thunder_comments_22[[jj]] <- get_all_comments2(thunder_ids2[jj])
  cat(paste0("\t",jj))
  BRRR::skrrrahh(jj)
}

thunder_comments_3 <- bind_rows(thunder_comments_22)

save(thunder_comments_3, file = "data/thunder3.Rdata")


thunder_ids3 <- thunder_ids2[178:length(thunder_ids2)]
thunder_comments_222 <- list()
for (jj in seq_along(thunder_ids3)) {  
  thunder_comments_222[[jj]] <- get_all_comments2(thunder_ids3[jj])
  cat(paste0("\t",jj))
  BRRR::skrrrahh(jj)
}

thunder_comments_4 <- bind_rows(thunder_comments_222)

save(thunder_comments_4, file = "data/thunder4.Rdata")

thunder_ids4 <- thunder_ids3[50:length(thunder_ids3)]
thunder_comments_2222 <- list()
for (jj in seq_along(thunder_ids4)) {  
  thunder_comments_2222[[jj]] <- get_all_comments2(thunder_ids4[jj])
  cat(paste0("\t",jj))
  BRRR::skrrrahh(jj)
}

thunder_comments_5 <- bind_rows(thunder_comments_2222)

save(thunder_comments_5, file = "data/thunder5.Rdata")

thunder_ids5 <- thunder_ids4[94:length(thunder_ids4)]
thunder_comments_22222 <- list()
for (jj in seq_along(thunder_ids5)) {  
  thunder_comments_22222[[jj]] <- get_all_comments2(thunder_ids5[jj])
  cat(paste0("\t",jj))
  BRRR::skrrrahh(jj)
}

thunder_comments_6 <- bind_rows(thunder_comments_22222)

save(thunder_comments_6, file = "data/thunder6.Rdata")

thunder_comments <- rbind(thunder_comments1, thunder_comments_2,
                          thunder_comments_3, thunder_comments_4,
                          thunder_comments_5, thunder_comments_6)

save(thunder_comments, file = "data/thunder_comments.Rdata")

```

# Sargon of Akkad

## Scraping

```{r}

## Try 1
sargon_comments1 <- extract_comments(sargon_ids, 1, "sargon")

sargon_comments <- sargon_comments1

```
# old scraper

- ACHTUNG! REMOVE THE (POSSIBLE) DUPLICATES!
- Test if 45 never works
- Test if 9 never works (in the second sample of 221)


```{r}

# extract function
extract_comments <- function(ids) {
  comments <- list()
  for (jj in seq_along(ids)) {
    comments[[jj]] <- get_all_comments2(ids[jj])
    cat(paste0("\t", jj))
  }
  comments <- suppressWarnings(bind_rows(comments))
  message(paste("\n\nIteration stopped at:", jj))
  return(comments)
}

ww <- c(amazingatheist_ids[1:2], "ss", amazingatheist_ids[1:3])

try_catch(extract_comments(ww), 
          .e = ~ paste0("There is an error: ", .x), 
          .w = ~ paste0("This is a warning: ", .x))



# Error : HTTP failure: 401 <- AUTH ERROR

# Error : HTTP failure: 400 <- nonproblematic
# Error : HTTP failure: 403 <- nonproblematic

# Try 1
# missed
c(44, 60, 61, 62, 73, 74, 88) # 7
amazingatheist_comments1 <- extract_comments(amazingatheist_ids)

count(unique(amazingatheist_comments1$videoId))

save(amazingatheist_comments1, file = "data/amazingatheist_comments1.Rdata")

# Try 2
 
amazingatheist_ids1 <- amazingatheist_ids[145:length(amazingatheist_ids)]
amazingatheist_comments2 <-  extract_comments(amazingatheist_ids1)

save(amazingatheist_comments2, file = "data/amazingatheist_comments2.Rdata")

# Try 3

amazingatheist_ids3 <- amazingatheist_ids1[jj:length(amazingatheist_ids1)]
amazingatheist_comments3 <-  extract_comments(amazingatheist_ids3)

save(amazingatheist_comments3, file = "data/amazingatheist_comments3.Rdata")




# old
 
amazingatheist_comments1 <- list()
for (jj in seq_along(amazingatheist_ids)) {  
  amazingatheist_comments1[[jj]] <- get_all_comments2(amazingatheist_ids[jj])
  cat(paste0("\t",jj))
}


save(amazingatheist_comments2, file = "data/amazingatheist_comments2.Rdata")

extract_comments <- function(ids) {
  comments <- list()
for (jj in seq_along(ids)) {  
  comments[[jj]] <- get_all_comments2(ids[jj])
  cat(paste0("\t",jj))
  }
  comments <- suppressWarnings( bind_rows(comments) )
  message(paste("\n\nIteration stopped at:", jj))
  return(comment)
}

ww <- c(amazingatheist_ids[1:2], "ss", amazingatheist_ids[1:3])
extract_comments(ww)

try_catch(lol <- extract_comments(ww), 
          .e = function(e){
            print(paste0("There is an error: ", e))
            print("Ok, let's save this")
            save(lol, "lol.Rdata") # commented to prevent from log.txt creation on your machine
            print(paste("log saved on log.txt at", time))
            print("let's move on now")
          })

x <- "HTTP sdg"
s <- str_detect(x, "HTTP")
# Stop if .x is numeric
b  <- 20
# Warn if .x is not equal to 10
warn_if_not(.x = x, 
        .p = ~ str_detect(.x, "fllap") , 
        msg = "b should be 10")

warn_if(.x = x, 
        .p = ~ str_detect(.x, "HTTP"), 
        msg = "b should be 10")

try_catch(fluuur <- extract_comments(ww), 
          .e = ~ warn_if(.x = .x, 
               .p = ~ if (str_detect(.x, "HTTP failure: 404")) save(fluuur, "fluuur.Rdat"), 
               msg = "I did it!"))

ids <- c("1", "3", "7", "9")

errors <- c("Error: Try Again", "Error: Stop for Loop")

  numbers <- list()
for (jj in seq_along(ids)) {  
  numbers[[jj]] <- as.numeric(ids[jj])
  if (jj == sample(1:4, 1)) stop(sample(errors, 1))
  }

numbers

  numbers <- list()
for (jj in seq_along(ids)) {  
  numbers[[jj]] <- as.numeric(ids[jj])
  }
  
  numbers
  
  safely <- function(fn, ..., max_attempts = 5) {
  function(...) {
    this_env <- environment()
    for(i in seq_len(max_attempts)) {
      ok <- tryCatch({
          assign("result", fn(...), envir = this_env)
          TRUE
        },
        error = function(e) {
          FALSE
        }
      )
      if(ok) {
        return(this_env$result)
      }
    }
    msg <- sprintf(
      "%s failed after %d tries; returning NULL.",
      deparse(match.call()),
      max_attempts
    )
    warning(msg)
    NULL
  }
  }
  
  
```
